<template>
  <div>
    <h1>AboutView</h1>
    
    <svg class="animate-bounce w-6 h-6">
    </svg>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto itaque, facere eos error voluptatum dolorum ex illum praesentium. Quis soluta est, dignissimos perspiciatis ipsa delectus itaque minima nobis minus commodi.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus ab blanditiis aspernatur a. Dolorum harum laboriosam distinctio ratione fugit. Beatae, consequatur. Quia a necessitatibus atque consequuntur. Laborum illo nemo dolores.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum quidem quod debitis dolor molestiae. Commodi perferendis quidem, molestiae tenetur hic adipisci? Placeat rerum deleniti hic aspernatur laboriosam et cum odit?</p>
  </div>
</template>

<script>
export default {
  name: 'AboutView',

  data() {
    return {
      
    };
  },

  mounted() {
    
  },

  methods: {
    
  },
};
</script>

<style lang="scss" scoped>

</style>